site_name: Multi Ifeval
theme: material
plugins:
  - include-markdown
  - search
  - include_dir_to_nav
  - mkapi
nav:
  - .
  - API Reference:
    - $api:src/multi_ifeval.***
    - $api:src/multi_bfcl.***
