name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-check:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"
      - run: uv sync --python 3.12 --locked --all-extras --dev
      - run: uv run --python 3.12 --locked pre-commit run --show-diff-on-failure --all-files

  pytest:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    permissions:
      contents: read
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"
      - run: uv sync --python 3.12 --locked --all-extras --dev
      - run: uv run --python 3.12 --locked pytest
